### ISSUE TITLE
Native pt-br translation in the plugin

### ISSUE THREAD

**Issue by NetoSantoos78** [NotMarra/NotCredits#7]
Add the pt-BR translation to the plugin, I really liked the plugin, you can create several things on top of it.

[pt_br.zip](https://github.com/user-attachments/files/17006104/pt_br.zip)

![image](https://github.com/user-attachments/assets/cf79c293-632c-4cb7-bec1-250951148977)

**Comment by NotMarra** [comment]
Thank you, I will add this language next update
